package de.ownmods.minimap.client;
import de.ownmods.settings.client.UiText;
import de.ownmods.settings.client.compat.InputCompat;
import de.ownmods.notes.client.NotesBridge;import de.ownmods.notes.core.Note;import java.util.*;import net.minecraft.client.gui.components.EditBox;import net.minecraft.client.gui.screens.Screen;import net.minecraft.client.input.KeyEvent;import net.minecraft.network.chat.Component;
final class WaypointEditScreen extends Screen {private final Screen parent;private final String id,dimension;private final int x,y,z;private String name,color,icon;private EditBox nameBox;private static final List<String> COLORS=List.of("red","green","blue","yellow","purple");private static final List<String> ICONS=List.of("minecraft:map","minecraft:compass","minecraft:lodestone","minecraft:nether_star","minecraft:diamond","minecraft:redstone_torch","minecraft:chest","minecraft:bell");
    WaypointEditScreen(Screen parent,String id,String name,String color,String icon,String dimension,int x,int y,int z){super(Component.literal(id==null?UiText.tr("vr.text.2fb154d5db52"):UiText.tr("vr.text.24362d5ca497")));this.parent=parent;this.id=id;this.name=name==null?UiText.tr("vr.text.1533799cc9bd"):name;this.color=COLORS.contains(color)?color:"blue";this.icon=icon==null?"minecraft:map":icon;this.dimension=dimension;this.x=x;this.y=y;this.z=z;}
    @Override protected void init(){int w=Math.min(360,width-20),l=(width-w)/2,t=Math.max(20,(height-210)/2);nameBox=addRenderableWidget(new EditBox(font,l+20,t+55,w-40,20,Component.literal(UiText.tr("vr.text.dcd1d5223f73"))));nameBox.setMaxLength(100);nameBox.setValue(name);nameBox.setResponder(v->name=v);addRenderableWidget(new MapUi.Action(l+20,t+85,(w-50)/2,20,UiText.tr("vr.text.2a335761aab2")+color,0xFF5A9BD5,()->{color=COLORS.get((COLORS.indexOf(color)+1)%COLORS.size());rebuild();}));addRenderableWidget(new MapUi.Action(l+30+(w-50)/2,t+85,(w-50)/2,20,UiText.tr("vr.text.fe9dcacaa599"),0xFF9D78C3,()->{icon=ICONS.get((ICONS.indexOf(icon)+1)%ICONS.size());rebuild();}));addRenderableWidget(new MapUi.Action(l+20,t+150,(w-50)/2,20,UiText.tr("vr.text.f7ff1178af20"),0xFFB65C52,()->minecraft.gui.setScreen(parent)));addRenderableWidget(new MapUi.Action(l+30+(w-50)/2,t+150,(w-50)/2,20,UiText.tr("vr.text.f6b2ff39f540"),0xFF5EA35A,this::save));setInitialFocus(nameBox);}
    private void rebuild(){clearWidgets();init();}
    private void save(){try{NotesBridge.saveWaypoint(id,name,color,icon,dimension,x,y,z);if(MinimapClient.session!=null)MinimapClient.session.refreshNotes();minecraft.gui.setScreen(parent);}catch(Exception e){minecraft.gui.setScreen(new SimpleMessageScreen(parent,UiText.tr("vr.text.38d2a69e5145"),e.getMessage()));}}
    @Override public void extractRenderState(net.minecraft.client.gui.GuiGraphicsExtractor g,int mx,int my,float d){super.extractRenderState(g,mx,my,d);int w=Math.min(360,width-20),l=(width-w)/2,t=Math.max(20,(height-210)/2);MapUi.raised(g,l,t,w,190,0xFFE3D4B9,0xFF4B8FC1);MapUi.text(g,title.getString(),l+20,t+16,0xFF2C2822);MapUi.text(g,dimension+" · "+x+" / "+y+" / "+z,l+20,t+37,0xFF5D554A);MapUi.text(g,UiText.tr("vr.text.4f36974eb26d"),l+20,t+118,0xFF5D554A);}
    @Override public boolean keyPressed(KeyEvent e){if(e.key()==InputCompat.code("KEY_RETURN")||e.key()==InputCompat.code("KEY_NUMPADENTER")){save();return true;}return super.keyPressed(e);}    
}
