ownmods_cropreplant.mode=PERSONAL
ownmods_cropreplant.rule.beetroots=PERSONAL
ownmods_cropreplant.rule.carrots=PERSONAL
ownmods_cropreplant.rule.enabled=PERSONAL
ownmods_cropreplant.rule.nether_wart=PERSONAL
ownmods_cropreplant.rule.potatoes=PERSONAL
ownmods_cropreplant.rule.right_click=PERSONAL
ownmods_cropreplant.rule.sneak_bypass=PERSONAL
ownmods_cropreplant.rule.wheat=PERSONAL
ownmods_cropreplant.server.bool.beetroots=true
ownmods_cropreplant.server.bool.carrots=true
ownmods_cropreplant.server.bool.enabled=true
ownmods_cropreplant.server.bool.nether_wart=true
ownmods_cropreplant.server.bool.potatoes=true
ownmods_cropreplant.server.bool.right_click=true
ownmods_cropreplant.server.bool.sneak_bypass=true
ownmods_cropreplant.server.bool.wheat=true
ownmods_gravestone.mode=SERVER_LOCKED
ownmods_gravestone.rule.chat_message=PERSONAL
ownmods_gravestone.rule.enabled=PERSONAL
ownmods_gravestone.rule.single_fallback=PERSONAL
ownmods_gravestone.server.bool.chat_message=true
ownmods_gravestone.server.bool.enabled=true
ownmods_gravestone.server.bool.single_fallback=true
ownmods_inventorysort.allowed.sort_mode=id,family,type,color
ownmods_inventorysort.mode=PERSONAL
ownmods_inventorysort.rule.buttons=PERSONAL
ownmods_inventorysort.rule.containers=PERSONAL
ownmods_inventorysort.rule.enabled=PERSONAL
ownmods_inventorysort.rule.merge=PERSONAL
ownmods_inventorysort.server.bool.buttons=true
ownmods_inventorysort.server.bool.containers=true
ownmods_inventorysort.server.bool.enabled=true
ownmods_inventorysort.server.bool.merge=true
ownmods_inventorysort.server.choice.sort_mode=family
ownmods_timber.mode=PERSONAL
ownmods_timber.rule.axe.minecraft\:copper_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:diamond_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:golden_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:iron_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:netherite_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:stone_axe=PERSONAL
ownmods_timber.rule.axe.minecraft\:wooden_axe=PERSONAL
ownmods_timber.rule.consume_saplings=FORCE_TRUE
ownmods_timber.rule.enabled=PERSONAL
ownmods_timber.rule.leaves=PERSONAL
ownmods_timber.rule.replant=PERSONAL
ownmods_timber.rule.sneak_bypass=PERSONAL
ownmods_timber.server.bool.axe.minecraft\:copper_axe=true
ownmods_timber.server.bool.axe.minecraft\:diamond_axe=false
ownmods_timber.server.bool.axe.minecraft\:golden_axe=true
ownmods_timber.server.bool.axe.minecraft\:iron_axe=true
ownmods_timber.server.bool.axe.minecraft\:netherite_axe=false
ownmods_timber.server.bool.axe.minecraft\:stone_axe=true
ownmods_timber.server.bool.axe.minecraft\:wooden_axe=true
ownmods_timber.server.bool.consume_saplings=true
ownmods_timber.server.bool.enabled=true
ownmods_timber.server.bool.leaves=true
ownmods_timber.server.bool.replant=true
ownmods_timber.server.bool.sneak_bypass=true
ownmods_toolswap.allowed.policy=same,same_or_worse,best
ownmods_toolswap.mode=PERSONAL
ownmods_toolswap.rule.allow_enchanted=PERSONAL
ownmods_toolswap.rule.auto_tool=PERSONAL
ownmods_toolswap.rule.enabled=PERSONAL
ownmods_toolswap.server.bool.allow_enchanted=true
ownmods_toolswap.server.bool.auto_tool=false
ownmods_toolswap.server.bool.enabled=true
ownmods_toolswap.server.choice.policy=best
schemaVersion=1
